# Generated by Django 5.2.7 on 2025-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consola', models.CharField(choices=[('ps4', 'PlayStation 4'), ('ps5', 'PlayStation 5')], max_length=10)),
                ('destacado', models.BooleanField(default=False)),
                ('imagen', models.CharField(blank=True, max_length=500)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['-destacado', 'nombre'],
            },
        ),
    ]
