# Generated by Django 5.2.7 on 2025-10-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
