# Generated by Django 5.2.7 on 2025-10-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_juego_genero_alter_juego_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='stock',
        ),
        migrations.AddField(
            model_name='juego',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
