# Generated by Django 5.2.7 on 2025-11-09 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_juego_stock_juego_disponible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={'ordering': ['nombre'], 'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.RemoveField(
            model_name='juego',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='genero',
        ),
        migrations.AddField(
            model_name='juego',
            name='es_solo_secundario',
            field=models.BooleanField(default=False, help_text='Indica si este juego solo existe como secundario (sin primario)'),
        ),
        migrations.AddField(
            model_name='juego',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='precio_secundario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del proveedor secundario', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='recargo_secundario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recargo del precio secundario', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='tiene_secundario',
            field=models.BooleanField(default=False, help_text='Indica si este juego tiene precio secundario disponible'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.CharField(default='img/default.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
