# Generated by Django 5.2.7 on 2025-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_juego_options_remove_juego_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del juego', null=True),
        ),
    ]
