# Generated by Django 5.2.4 on 2025-11-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_juego_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
