# Generated by Django 5.2.4 on 2025-11-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_juego_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Utilidad',
                'verbose_name_plural': 'Utilidades',
                'managed': False,
            },
        ),
    ]
