# Generated by Django 5.2.4 on 2025-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_utilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('juego', models.CharField(max_length=200)),
                ('reseña', models.TextField()),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reseña de Cliente',
                'verbose_name_plural': 'Reseñas de Clientes',
            },
        ),
    ]
