# Generated by Django 5.2.4 on 2025-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_resenacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenacliente',
            name='puntuacion',
        ),
        migrations.AlterField(
            model_name='resenacliente',
            name='cliente',
            field=models.CharField(help_text='Usuario de Instagram', max_length=100),
        ),
    ]
