# Generated by Django 5.2.4 on 2025-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_resenacliente_puntuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenacliente',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen (opcional)', max_length=255, null=True),
        ),
    ]
