# Generated by Django 5.2.4 on 2025-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_resenacliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenacliente',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen (se busca automáticamente)', max_length=255, null=True),
        ),
    ]
